ZSH_THEME_GIT_PROMPT_PREFIX="🌴 %{$fg[magenta]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_DIRTY=" ✏️"
ZSH_THEME_GIT_PROMPT_UNTRACKED=" ❓"
ZSH_THEME_GIT_PROMPT_CLEAN=""

PROMPT='%c $(git_prompt_info)➜ '
